
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rsvpcustomer2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rsvpcustomer2
    spec:
      containers:
      - name: rsvp-app
        image: teamcloudyuga/rsvpapp
        env:
        - name: MONGODB_HOST
          value: 10.0.0.127
        - name: TEXT1
          valueFrom:
            configMapKeyRef:
              name: customer2
              key: TEXT1
        - name: TEXT2
          valueFrom:
            configMapKeyRef:
              name: customer2
              key: TEXT2
        - name: COMPANY
          valueFrom:
            configMapKeyRef:
              name: customer2
              key: COMPANY
        ports:
        - containerPort: 5000
          name: web-port
